services:

  # external images
  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=microservices

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      AWS_DEFAULT_REGION: us-west-1
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      EDGE_PORT: 4566
      SERVICES: s3
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - ./awslocal-init-scripts:/docker-entrypoint-initaws.d
      - "${TEMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: 'elasticsearch'
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/var/lib/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  logstash:
    image: logstash:7.12.0
    container_name: 'logstash'
    volumes:
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines:/usr/share/logstash/config/pipelines:ro
      - shared-volume:/logs
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    networks:
      - elastic
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.12.0
    container_name: 'kibana'
    ports:
      - target: 5601
        published: 5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

  # local images
  eureka:
    image: eureka-service-img
    container_name: eureka
    build: ../eureka-service/
    ports:
      - "8761:8761"

  gateway:
    container_name: spring-gateway
    image: spring-gateway-img
    build: ../spring-gateway/
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka

  resource-service:
    container_name: resource-service
    image: resource-service-img
    build: .
    volumes:
      - shared-volume:/logs
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - localstack
      - rabbitmq
      - postgresql
      - storage-service

  song-service:
    container_name: song-service
    image: song-service-img
    build: ../song-service/
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - postgresql

  resource-processor:
    container_name: resource-processor
    image: resource-processor-img
    build: ../resource-processor/
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - rabbitmq
      - song-service
      - resource-service

  storage-service:
    container_name: storage-service
    image: storage-service-img
    build: ../storage-service/
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - localstack
      - postgresql



volumes:
  es_data:
    driver: local
  shared-volume:

networks:
  elastic:
    name: elastic
    driver: bridge
