server:
  port: 8087
security:
  basic:
    enable: false
aws:
  region: us-west-1
  credentials:
    access-key: test
    secret-key: test
  s3:
    bucket: resource-bucket
    endpoint: http://127.0.0.1:4566
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      create: Resources.Create
      create_dead: Resources.Create.Dead
      delete: Resources.Delete
      delete_dead: Resources.Delete.Dead
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
song:
  service:
    connect:
      timeout: 2000
    read:
      timeout: 2000
    baseUrl: http://localhost:8088/songs